import jquery320 from './jquery-3.2.0.min';
// import modern from './modernizr.min';
import pace from './pace.min';
// import barba from './barba.min';
import lazysizes from './lazysizes.min';
import velocity from './velocity.min';
import velocityUI from './velocity-ui.min';
import parallax from './parallax';
// import scrollie from './scrollreveal.min';
import picturefill from './picturefill.min';
// import mainJS from './main';

jquery320();
// modern();
pace();
// barba();
lazysizes();
velocity();
velocityUI();
parallax();
// scrollie();
// mainJS();
